name: .NET

on:
  #pull_request:
    #types: [opened]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Build
      run: msbuild MauiApp1/MauiApp1.csproj -r -p:Configuration=Release -p:RestorePackages=false -p:TargetFramework=net6.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: windows-ci-build
        path: MauiApp1/bin/Release/net6.0-windows*/**/MauiApp1*.msix
