name: Post hello world
on:
  pull_request:
    types: [opened]
    
permissions:
  contents: write
  issues: write
  actions: write
  pull-requests: write
jobs:
  build:
    name: Post Hello World
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Hello World"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
