name: Post hello world
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  build:
    name: Post Hello World
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Hello World"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
